version: "3"

services:

  rabbitmq:
    image: "rabbitmq:management-alpine"
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      AMPQ_ADDRESS: "amqp://rabbitmq:5672"

  shortest-path-computing-service:
    image: "oterrien/shortest-path-computing-service:1.0"
    links:
      - rabbitmq
    environment:
      ENV: "development"
      AMPQ_ADDRESS: "amqp://rabbitmq:5672"

  uploading-service:
    image: "oterrien/uploading-service:1.0"
    ports:
      - "8081:8080"
    links:
      - rabbitmq
    environment:
      ENV: "development"
      AMPQ_ADDRESS: "amqp://rabbitmq:5672"
	  
  reporting-service:
    image: "oterrien/reporting-service:1.0"
    ports:
      - "8082:8080"
    links:
      - rabbitmq
    environment:
      ENV: "development"
      AMPQ_ADDRESS: "amqp://rabbitmq:5672"
